### ISSUE TITLE
[BUG] "incompatability with immers FX"

### ISSUE THREAD

**Issue by supershorty1** [Traben-0/Entity_Texture_Features#100]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-log channel*

**Describe the issue**
- What happened? crashed on game start

**Screenshots**
- If applicable, add screenshots to help explain your problem.

**Crash log**
[crash-2022-08-27_21.30.46-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/9438073/crash-2022-08-27_21.30.46-client.txt)

**Your setup: (please complete the following information):**
 - Minecraft version: 1.18.2
 - Modloader: forge
 - ETF Version 40.1.73
 - Does the issue persist with only ETF (and cloth config for forge versions) installed?

**Comment by Traben-0** [comment]
i'll have to look into this further but first glance looks like immersive FX will need to fix something

**Comment by Traben-0** [comment]
Apologies for the late reply, i've been on vacation.
As far as i can tell immersive FX is crashing due to errors in it's own code and ETF just happens to be in the stack trace. That part of ETFs code is also very unlikely to cause a compatability issue, as it is entirely self contained.

Immersive FX's issue tracker is here: https://github.com/Y3Z0N/ImmersiveFX/issues

If you want a working sound mod, I use soundphysics in my personal mod list, it is updated to 1.19 already :)
