### ISSUE TITLE
[BUG] "Entity texture with custom name "

### ISSUE THREAD

**Issue by firyy** [Traben-0/Entity_Texture_Features#107]
I'm trying to use my "iron_golem3" only when it has a custom name but it doesn't seem to be working, am I doing something wrong?

My iron_golem.properties :

skins.1=1 2
weights.1=3 1

name.2=Shrek     ( also tried iregex:.*(Shrek).* )
skins.2=3

- Minecraft version: 1.19.2
- ModLoader: Fabric
- ETF Version 4.1.1

**Comment by Traben-0** [comment]
this is a very simple fix
the "named" case needs to be first

they are all checked in order and because case 1 has no conditions it gets selected every time

the 'named' case should be skins.1 & name.1, then it will check that first and only apply skins.1 to a mob with that name, failing that it will move to case 2
