### ISSUE TITLE
[BUG] "Crashes server on startup"

### ISSUE THREAD

**Issue by DTX3** [Traben-0/Entity_Texture_Features#118]
When starting my server it crashes with this installed.

I'm using 1.18.2-4.1.1 forge version.

Failure message: Entity Texture Features (entity_texture_features) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 4.1.1
	Mod Issue URL: https://github.com/Traben-0/EmissiveMod/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER

Crash log.

[crash-2022-11-14_11.58.35-fml.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10002763/crash-2022-11-14_11.58.35-fml.txt)

**Comment by Traben-0** [comment]
yes ETF is a client side only mod, it crashes forge if it detects it is being run on a dedicated server

**Comment by Traben-0** [comment]
you need to install it on your client only, the dedicated server does not need the mod and it does not do anything on the server

**Comment by DTX3** [comment]
Oh whoops! Apologies.

**Comment by Traben-0** [comment]
all good mate it happens :)

**Comment by electricsteve** [comment]
@Traben-0 could you at least just make it so it doesn't load anything on the server? It is pretty hard to find that ETF is causing it. And it got on the server because when installing a modpack it just does that... 
EDIT: when I export my modpack it's marked as `"server": "required"` so my server installer downloads it.

<img width="904" height="96" alt="Image" src="https://github.com/user-attachments/assets/66b8f465-543f-4329-b383-001c24690f15" />
