### ISSUE TITLE
[BUG] ETF 4.3.0+ overrides modded boats' models

### ISSUE THREAD

**Issue by SplendidAlakey** [Traben-0/Entity_Texture_Features#152]
**Describe the issue**

Some modded boats' models get overridden by the default oak boat, when ETF 4.3.0 or above is installed. For example Azalea and Jacaranda boats from Aurora's Decorations. Downgrading to 4.2.0 or lower solves the issue.

**Screenshots**

With ETF 4.3.3
![2023-03-10_04 34 29](https://user-images.githubusercontent.com/86702831/224217357-75a08059-3721-468c-9995-3641859ba119.png)

With ETF 4.2.0
![2023-03-10_04 40 16](https://user-images.githubusercontent.com/86702831/224217844-80ffc7e6-c891-4b29-899a-3234b2aa700e.png)

**Logs**

https://gist.github.com/SplendidAlakey/f0a7510157253309e4978b4024359fdf#file-latest_4-3-3-log

https://gist.github.com/SplendidAlakey/f0a7510157253309e4978b4024359fdf#file-latest_4-2-0-log

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.2
- ModLoader: Quilt 0.18.3
- ETF Version 4.3.3 (4.3.0+)
- Does the issue persist with only ETF installed? - No, as there's nothing to break
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? - Yes

**Comment by Traben-0** [comment]
strange, I will look into this

**Comment by Traben-0** [comment]
i havent tested with the mentioned mod but i have redone the boat code so that it will respect any mods changes to this method in BoatEntityRenderer, which "should" be how most mod try and set new boat textures
![image](https://user-images.githubusercontent.com/8456487/226085834-3cea8785-e269-4c2a-a5c0-207c177b18b7.png)

this fix will be in 4.3.5 when its out

**Comment by Traben-0** [comment]
marking this as fixed, feel free to reopen if it breaks again
