### ISSUE TITLE
When the villagers swim, they die, because don't float.

### ISSUE THREAD

**Issue by wilebaldo** [Traben-0/Entity_Texture_Features#251]
I don't know if this a bug or is normal on the mod, but when I used the animation for the villagers make them don't float all the way up and in my trading hall I have I use water to move them and when that happens sometimes the villager don't float and they die under the water.

This is the picture how they looks with and without the mod.

![2024-02-18_22 16 35](https://github.com/Traben-0/Entity_Texture_Features/assets/8034131/098cec77-3bb4-4417-a3db-cbf385c41fa6)

![2024-02-18_22 20 32](https://github.com/Traben-0/Entity_Texture_Features/assets/8034131/5de29bd4-99ce-4c6b-b985-a57bd472d368)

**Comment by Traben-0** [comment]
fresh animations moves them visually down to appear to swim

they are not actuially down further and cannot be drowning due to this as it is only visual, press F3 + B to see their hitboxes and you will see they are at the same height with just the animated model moved down visually when in water

something else is killing your villagers
